### ISSUE TITLE
Jenkins and GitHub actions

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/scripts#37]
I will update this issue.
```dockerfile

# Install PHP and composer
RUN apt-get update
# https://packages.sury.org/php/README.txt
RUN apt-get -y install apt-transport-https lsb-release ca-certificates curl
RUN curl -sSL -o /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
RUN apt-get update
RUN apt-get install -y php7.3 php7.3-xdebug php7.3-xsl php7.3-dom php7.3-xml php7.3-zip php7.3-mbstring php7.3-mysqli php7.3-recode php7.3-curl
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt update && apt install -y yarn
RUN curl -sSL -o /bin/pdepend https://github.com/pdepend/pdepend/releases/download/2.8.0/pdepend.phar && chmod +x /bin/pdepend
RUN curl -sSL -o /bin/phpmd https://github.com/phpmd/phpmd/releases/download/2.9.1/phpmd.phar && chmod +x /bin/phpmd
RUN curl -sSL -o /bin/phploc https://phar.phpunit.de/phploc.phar && chmod +x /bin/phploc
RUN curl -sSL -o /bin/phpcpd https://phar.phpunit.de/phpcpd.phar && chmod +x /bin/phpcpd
RUN curl -sSL -o /bin/doctum https://doctum.long-term.support/releases/5/doctum.phar && chmod +x /bin/doctum
RUN curl -sSL -o /bin/phpcb https://github.com/mayflower/PHP_CodeBrowser/releases/download/2.3.1/phpcb-2.3.1.phar && chmod +x /bin/phpcb
RUN apt install -y gettext
```

## GH runner
`docker-compose.yml`
```yml
version: "3.1"

services:
  github-wdes-worker:
    restart: on-failure:5
    image: myoung34/github-runner:latest
    environment:
      ORG_NAME: wdes
      RUNNER_NAME_PREFIX: wdes-github-runner
      ACCESS_TOKEN: "${GITHUB_WDES_ORG_RUNNER_ACCESS_TOKEN}"
      RUNNER_WORKDIR: /tmp/runner/work
      RUNNER_GROUP: default
      ORG_RUNNER: "true"
      LABELS: linux,x64,self-hosted,ubuntu-latest,wdes
    dns_search: wdes.local
    hostname: github-wdes-worker.wdes.local
    domainname: wdes.local
    networks:
      gharunnerlocal:
        aliases:
          - github-wdes-worker
          - github-wdes-worker.wdes.local
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/runner:/tmp/runner"

networks:
  gharunnerlocal:
    driver: bridge
```
`.env`
```env
GITHUB_WDES_ORG_RUNNER_ACCESS_TOKEN=replaceMePatSeeRunneReadmeForGrants
```
